"""Step 09: build the paper's LaTeX tables and statistics macros from the result JSONs.

Run:  python scripts/09_make_tables.py [--out-dir DIR]
Writes tab_*.tex and crossover_stats*.tex to tables/ in this repo, or to --out-dir.
"""
from __future__ import annotations

import argparse
import json
import logging
import math
import re
from pathlib import Path
from typing import Dict, List, Optional

import numpy as np
from scipy import stats as _st

import sys as _sys
from pathlib import Path as _Path

# repo root on the path, for config and src
_sys.path.insert(0, str(_Path(__file__).resolve().parents[1]))

import config

logging.basicConfig(level=config.CONFIG.log_level,
                    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s")
log = logging.getLogger("tables")

DATASETS = ["amazon", "yelpchi", "ieee_cis"]
# 'ours' rows: the label-free lifting (lambda=0, no generation)
OURS_KEY = "none|lam0"
PRETTY = {"amazon": "Amazon", "yelpchi": "YelpChi", "ieee_cis": "IEEE-CIS"}
# (baselines.json key, row label) of the static tables
_METHOD_ROWS = [("mlp", "MLP (features)"), ("rf", "Random Forest"),
                ("gcn", "GCN"), ("bwgnn", "BWGNN"),
                ("fixed_hg", "Fixed higher-order (HGNN-style)")]
TABLES_DIR = config.ROOT / "tables"


def _result(ds: str, name: str) -> Path:
    """results/<ds>/<name>."""
    return config.RESULTS / ds / name


def _result_glob(ds: str, pattern: str) -> List[Path]:
    """Files in results/<ds>/ matching pattern."""
    return sorted((config.RESULTS / ds).glob(pattern))


def _load(path: Path) -> dict:
    """Load a result JSON."""
    return json.loads(path.read_text())


def _ms(d: dict, metric: str) -> str:
    """mean±std of a metric block."""
    m = d[metric]
    return f"{m['mean']:.3f}\\,$\\pm$\\,{m['std']:.3f}"


def _write(name: str, body: str) -> None:
    TABLES_DIR.mkdir(parents=True, exist_ok=True)
    (TABLES_DIR / name).write_text(body)
    log.info("wrote %s", TABLES_DIR / name)


def table_datasets() -> None:
    """Dataset statistics (tab_datasets.tex)."""
    rows = []
    for ds in DATASETS:
        s = _load(_result(ds, "stats.json"))
        rows.append(
            f"{PRETTY[ds]} & {s['num_nodes']:,} & {s['homo']['num_edges']:,} & "
            f"{100*s['fraud_rate']:.1f}\\% & {s['homo']['node_homophily']:.2f} & "
            f"{s['homo']['fraud_neighbor_heterophily']:.2f} & "
            f"{s['candidates']['mean_fraud_purity']:.2f} \\\\"
        )
    body = (
        "% auto-generated by 09_make_tables.py\n"
        "\\begin{tabular}{lrrrrrr}\n\\toprule\n"
        "Dataset & Nodes & Edges & Fraud & Node-hom. & Fraud$\\to$benign & Cell purity \\\\\n"
        "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n"
    )
    _write("tab_datasets.tex", body)


def table_leaderboard() -> None:
    """AP per method and dataset (tab_leaderboard.tex); 'ours' is none|lam0 from the ablation."""
    cols = {ds: _load(_result(ds, "baselines.json")) for ds in DATASETS}
    ours = {ds: _load(_result(ds, "ablation_results.json"))[OURS_KEY] for ds in DATASETS}

    lines = []
    for key, label in _METHOD_ROWS:
        cells = " & ".join(_ms(cols[ds][key], "ap") for ds in DATASETS)
        lines.append(f"{label} & {cells} \\\\")
    lines.append("\\midrule")
    ours_cells = " & ".join(_ms(ours[ds], "ap") for ds in DATASETS)
    lines.append(f"\\textbf{{Learnable lifting (ours)}} & {ours_cells} \\\\")

    header = " & ".join(PRETTY[d] for d in DATASETS)
    body = (
        "% auto-generated by 09_make_tables.py -- Average Precision (AP), 5 seeds\n"
        f"\\begin{{tabular}}{{l{'c'*len(DATASETS)}}}\n\\toprule\n"
        f"Method & {header} \\\\\n\\midrule\n" + "\n".join(lines) +
        "\n\\bottomrule\n\\end{tabular}\n"
    )
    _write("tab_leaderboard.tex", body)


def table_ablation() -> None:
    """Generation ablation at lambda=0: label, none, unsup, random (AP)."""
    modes = [("label|lam0", "Label carving"), ("none|lam0", "No generation"),
             ("unsup|lam0", "Unsup. (dense-half)"), ("random|lam0", "Random-half")]
    per_ds = {ds: _load(_result(ds, "ablation_results.json")) for ds in DATASETS}
    lines = []
    for key, label in modes:
        cells = " & ".join(_ms(per_ds[ds][key], "ap") for ds in DATASETS)
        lines.append(f"{label} & {cells} \\\\")
    header = " & ".join(PRETTY[d] for d in DATASETS)
    body = (
        "% auto-generated by 09_make_tables.py -- generation ablation, AP, lambda=0\n"
        f"\\begin{{tabular}}{{l{'c'*len(DATASETS)}}}\n\\toprule\n"
        f"Cell generation & {header} \\\\\n\\midrule\n" + "\n".join(lines) +
        "\n\\bottomrule\n\\end{tabular}\n"
    )
    _write("tab_ablation.tex", body)


def table_selection() -> None:
    """Selection study: AP and cell purity across the lambda sweep (tab_selection.tex).

    lambda > 0 comes from method_results.json (fixed pool, lambda varies); lambda = 0 is
    the label-carving run of the generation ablation (ablation_results.json).
    """
    def _by_lambda(res: dict) -> Dict[float, dict]:
        """Blocks by lambda from the 'label|lam<lambda>' keys (the selection study's pool)."""
        out: Dict[float, dict] = {}
        for k, v in res.items():
            m = re.fullmatch(r"label\|lam([0-9.eE+-]+)", k)
            if m:
                out[float(m.group(1))] = v
        return out

    per_ds: Dict[str, Dict[float, dict]] = {}
    for ds in DATASETS:
        per_ds[ds] = _by_lambda(_load(_result(ds, "method_results.json")))
        per_ds[ds][0.0] = _load(_result(ds, "ablation_results.json"))["label|lam0"]
    lams = sorted({lam for d in per_ds.values() for lam in d})

    def block(metric: str, title: str) -> List[str]:
        out = [f"\\multicolumn{{{len(DATASETS)+1}}}{{l}}{{\\emph{{{title}}}}} \\\\"]
        for lam in lams:
            cells = " & ".join(_ms(per_ds[ds][lam], metric) for ds in DATASETS)
            out.append(f"${lam:g}$ & {cells} \\\\")
        return out

    header = " & ".join(PRETTY[d] for d in DATASETS)
    lines = block("ap", "Average Precision") + ["\\midrule"] + \
        block("sel_fraud_purity", "Gate-weighted fraud purity of the cells")
    body = (
        "% auto-generated by 09_make_tables.py -- selection study, AP + selected-cell\n"
        "% purity across the lambda sweep, 5 seeds (candidate pool fixed)\n"
        f"\\begin{{tabular}}{{l{'c'*len(DATASETS)}}}\n\\toprule\n"
        f"$\\lambda$ & {header} \\\\\n\\midrule\n" + "\n".join(lines) +
        "\n\\bottomrule\n\\end{tabular}\n"
    )
    _write("tab_selection.tex", body)


def table_secondary() -> None:
    """recall@K and best-F1 per method and dataset (tab_secondary.tex)."""
    cols = {ds: _load(_result(ds, "baselines.json")) for ds in DATASETS}
    ours = {ds: _load(_result(ds, "ablation_results.json"))[OURS_KEY] for ds in DATASETS}

    def block(metric: str, title: str) -> List[str]:
        out = [f"\\multicolumn{{{len(DATASETS)+1}}}{{l}}{{\\emph{{{title}}}}} \\\\"]
        for key, label in _METHOD_ROWS:
            cells = " & ".join(_ms(cols[ds][key], metric) for ds in DATASETS)
            out.append(f"{label} & {cells} \\\\")
        cells = " & ".join(_ms(ours[ds], metric) for ds in DATASETS)
        out.append(f"\\textbf{{Learnable lifting (ours)}} & {cells} \\\\")
        return out

    header = " & ".join(PRETTY[d] for d in DATASETS)
    lines = block("recall@k", "recall@$K$") + ["\\midrule"] + \
        block("best_f1", "best-$F_1$")
    body = (
        "% auto-generated by 09_make_tables.py -- recall@K and best-F1, 5 seeds\n"
        f"\\begin{{tabular}}{{l{'c'*len(DATASETS)}}}\n\\toprule\n"
        f"Method & {header} \\\\\n\\midrule\n" + "\n".join(lines) +
        "\n\\bottomrule\n\\end{tabular}\n"
    )
    _write("tab_secondary.tex", body)


# gate diagnostics of the lifting in the D(mu) grid: (result key, column title)
_SYN_DIAG = [("frac_fraud_covered", "Train fraud covered"), ("mean_soft_a", "Mean gate"),
             ("sel_fraud_purity", "Gate-weighted purity")]


def _diag_mean(block: dict, key: str) -> str:
    """Seed mean of one diagnostic, or '--' where no seed has one (NaN)."""
    v = block[key]["mean"]
    return "--" if v != v else f"{v:.3f}"


def table_synthetic() -> None:
    """D(mu) grid: AP of rf, lambda=0 and positive lambda per delta x mu (tab_synthetic.tex),
    with the paired lambda=0 - rf and positive lambda - lambda=0 gaps, and the gate
    diagnostics of both liftings (tab_synthetic_diag.tex)."""
    res = _load(_result("synthetic", "synthetic_results.json"))
    def _aps(block: dict) -> dict:
        # values are in seed order and rows of a cell share instance and split,
        # so pairing by position is valid
        return {"aps": block["ap"]["values"]}

    lines, diag = [], []
    lam_hi = set()
    for delta in sorted((k for k in res if not k.startswith("_")), key=float):
        for mu in sorted(res[delta].keys(), key=float):
            c = res[delta][mu]
            lam_keys = [k for k in c if k != "rf"]
            lam_hi.add(float(max(lam_keys, key=float)))
            l0 = min(lam_keys, key=float); l1 = max(lam_keys, key=float)
            rf = _ms(c["rf"], "ap")
            a0 = _ms(c[l0], "ap"); a1 = _ms(c[l1], "ap")
            t_l = _pair_test(_aps(c[l1]), _aps(c[l0]))
            t_z = _pair_test(_aps(c[l0]), _aps(c["rf"]))
            gaps = " & ".join(f"${_num(t['diff'] * 100, '+.1f')}$ (${_fmt_p(t['p'])}$)"
                              for t in (t_z, t_l))
            lines.append(f"{float(delta):.1f} & {float(mu):.1f} & {rf} & {a0} & {a1} & {gaps} \\\\")
            diag.append(f"{float(delta):.1f} & {float(mu):.1f} & "
                        + " & ".join(_diag_mean(c[lam], key)
                                     for key, _ in _SYN_DIAG for lam in (l0, l1)) + " \\\\")
    # name the positive lambda if every cell used the same one
    hi = (f"$\\lambda{{=}}{lam_hi.pop():g}$" if len(lam_hi) == 1 else "$\\lambda{>}0$")
    body = (
        "% auto-generated by 09_make_tables.py -- D(mu) synthetic sweep, AP\n"
        "\\begin{tabular}{ccccccc}\n\\toprule\n"
        f"$\\Delta$ & $\\mu$ & RF (feat.) & $\\lambda{{=}}0$ & {hi} & "
        f"$\\lambda{{=}}0$ $-$ RF & {hi} $-$ $\\lambda{{=}}0$ \\\\\n"
        "\\midrule\n" + "\n".join(lines) + "\n\\bottomrule\n\\end{tabular}\n"
    )
    _write("tab_synthetic.tex", body)
    groups = " & ".join(f"\\multicolumn{{2}}{{c}}{{{title}}}" for _, title in _SYN_DIAG)
    rules = "".join(f"\\cmidrule(lr){{{3 + 2 * i}-{4 + 2 * i}}}" for i in range(len(_SYN_DIAG)))
    lams = " & ".join(f"$\\lambda{{=}}0$ & {hi}" for _ in _SYN_DIAG)
    _write("tab_synthetic_diag.tex",
           "% auto-generated by 09_make_tables.py -- D(mu) gate diagnostics, means over seeds\n"
           f"\\begin{{tabular}}{{cc{'c' * 2 * len(_SYN_DIAG)}}}\n\\toprule\n"
           f" & & {groups} \\\\\n{rules}\n$\\Delta$ & $\\mu$ & {lams} \\\\\n\\midrule\n"
           + "\n".join(diag) + "\n\\bottomrule\n\\end{tabular}\n")


def _seed_pairs(x: dict, y: dict) -> Optional[List[tuple]]:
    """Per-seed (x, y) AP pairs, or None if the blocks cannot be paired.

    Pairs by seed id when both carry 'seeds' (failed seeds are None and dropped),
    otherwise by position, only for equal lengths."""
    ax, ay = x.get("aps"), y.get("aps")
    if ax is None or ay is None:
        return None
    sx, sy = x.get("seeds"), y.get("seeds")
    if sx is not None and sy is not None and len(sx) == len(ax) and len(sy) == len(ay):
        my = dict(zip(sy, ay))
        pairs = [(a, my[s]) for s, a in zip(sx, ax) if s in my]
    elif len(ax) == len(ay):
        pairs = list(zip(ax, ay))
    else:
        return None
    return [(float(a), float(b)) for a, b in pairs
            if a is not None and b is not None and a == a and b == b]


_NAN_TEST = {"diff": float("nan"), "t": float("nan"), "df": float("nan"), "p": float("nan"),
             "lo": float("nan"), "hi": float("nan")}


def _pair_test(x: dict, y: dict) -> Dict[str, float]:
    """Paired t-test of x - y in AP over seeds; NaN when fewer than two seeds pair.

    Arms share the split within a seed, which is what makes the pairing valid.
    Returns diff, t, df, two-sided p and the 95% CI (lo, hi)."""
    pairs = _seed_pairs(x, y)
    if pairs is None or len(pairs) < 2:
        return dict(_NAN_TEST)
    d = np.asarray([a - b for a, b in pairs], float)
    n = d.size
    diff, sd = float(d.mean()), float(d.std(ddof=1))
    se, df = sd / math.sqrt(n), n - 1
    if not se > 0:
        return dict(_NAN_TEST, diff=diff, df=df)
    tval = diff / se
    half = float(_st.t.ppf(0.975, df)) * se
    return {"diff": diff, "t": float(tval), "df": float(df),
            "p": float(2.0 * _st.t.sf(abs(tval), df)),
            "lo": diff - half, "hi": diff + half}


def _second_half(block: dict) -> dict:
    """The block restricted to the second half of its seeds, for a replication check."""
    k = len(block["seeds"]) // 2
    return {"seeds": block["seeds"][k:], "aps": block["aps"][k:]}


_PAIRS = [("D", "A"), ("D", "B"), ("C", "A"), ("C", "B"), ("D", "C"), ("B", "A")]
# the arm pairs whose tests the paper quotes as macros (tab_crossover_summary, the
# introduction); tab_paired_arms prints every pair of _PAIRS
_MACRO_PAIRS = [("D", "A"), ("D", "B"), ("B", "A")]
_ARM_KEYS = {"A": "A_features", "B": "B_temporal_cols",
             "C": "C_label_cells", "D": "D_temporal_cells"}
_FULL = "1"   # result key of the full-label level


def _p_text(p: float) -> str:
    """p-value in math mode: <10^{-4} below 1e-4, else 3 decimals (4 below 0.001)."""
    if p < 1e-4:
        return "<10^{-4}"
    return f"{p:.3f}" if p >= 1e-3 else f"{p:.4f}"


def _fmt_p(p: float) -> str:
    """p-value text for use inside math mode, e.g. p<10^{-4} or p{=}0.013."""
    if p != p:
        return "p{=}\\text{--}"
    s = _p_text(p)
    return "p" + (s if s.startswith("<") else "{=}" + s)


def _num(x: float, fmt: str) -> str:
    """Number for a LaTeX macro; '--' if NaN, and a rounded zero without sign."""
    if x != x:
        return "--"
    s = format(x, fmt)
    return s.lstrip("+-") if float(s) == 0 else s


def _macros(tag: str, r: Dict[str, float]) -> List[str]:
    """Gap (AP points), t, df, p and 95% CI of one test as LaTeX macros named by tag."""
    lo, hi = r["lo"] * 100, r["hi"] * 100
    ci = "--" if lo != lo else f"[{lo:+.1f},{hi:+.1f}]"
    return [
        f"\\newcommand{{\\gap{tag}}}{{{_num(r['diff'] * 100, '+.1f')}}}",
        f"\\newcommand{{\\tstat{tag}}}{{{_num(r['t'], '.1f')}}}",
        f"\\newcommand{{\\dof{tag}}}{{{_num(r['df'], '.0f')}}}",
        f"\\newcommand{{\\pval{tag}}}{{{_fmt_p(r['p'])}}}",
        f"\\newcommand{{\\ci{tag}}}{{{ci}}}",
        f"% {tag}: diff={r['diff']*100:+.3f} t={r['t']:.3f} "
        f"df={r['df']:.2f} p={r['p']:.3g} CI=[{lo:+.3f},{hi:+.3f}]",
    ]


def table_temporal_crossover(dataset: str = "elliptic",
                             tab_name: str = "tab_crossover.tex",
                             stats_name: str = "crossover_stats.tex",
                             suffix: str = "") -> None:
    """Crossover table and significance macros for one temporal dataset.

    `suffix` keeps macro names distinct across datasets (e.g. gapDBFullDG for dgraph)."""
    res = _load(_result(dataset, "temporal_crossover.json"))
    # B: columns summarizing D's cells; D: label-free lifting; E: GCN on B's graph
    arms = [("A_features", "A: features (MLP)"), ("B_temporal_cols", "B: + columns of D's cells"),
            ("C_label_cells", "C: + label-carved cells"), ("D_temporal_cells", "D: label-free lifting (ours)"),
            ("E_temporal_gnn", "E: GCN with B's columns")]
    # keep arms present in the results (E is opt-in)
    arms = [(k, lab) for k, lab in arms if k in res]
    # levels from an arm block, not from metadata keys like _config
    levels = sorted(res["A_features"].keys(), key=float, reverse=True)

    def _ap(block: dict) -> str:  # crossover blocks are flat: AP mean/std at top level
        if block["mean"] != block["mean"]:   # every seed failed
            return "--"
        return f"{block['mean']:.3f}\\,$\\pm$\\,{block['std']:.3f}"

    lines = []
    for key, label in arms:
        cells = " & ".join(_ap(res[key][lv]) for lv in levels)
        row = f"\\textbf{{{label}}}" if key == "D_temporal_cells" else label
        lines.append(f"{row} & {cells} \\\\")
    # ROC-AUC diagnostic rows ('--' for an arm whose seeds all failed)
    lines.append("\\midrule\n\\multicolumn{%d}{l}{\\emph{ROC-AUC (diagnostic)}} \\\\" % (len(levels) + 1))
    for key, label in arms:
        cells = " & ".join(f"{res[key][lv]['auc_mean']:.3f}" if "auc_mean" in res[key][lv] else "--"
                           for lv in levels)
        lines.append(f"{label} & {cells} \\\\")
    header = " & ".join(f"{float(lv):g}" for lv in levels)
    body = (
        f"% auto-generated -- {dataset} temporal crossover, AP+AUC, "
        f"{res['A_features'][levels[0]]['n']} seeds\n"
        f"\\begin{{tabular}}{{l{'c'*len(levels)}}}\n\\toprule\n"
        f"Arm \\textbackslash{{}} labeled-positive frac & {header} \\\\\n\\midrule\n"
        + "\n".join(lines) + "\n\\bottomrule\n\\end{tabular}\n"
    )
    _write(tab_name, body)

    tests = {(a, b): _pair_test(res[_ARM_KEYS[a]][_FULL], res[_ARM_KEYS[b]][_FULL])
             for a, b in _MACRO_PAIRS}
    _write(stats_name,
           f"% auto-generated -- {dataset} crossover: paired tests at full labels "
           "(gap in AP points, t, df, p, 95% CI)\n"
           + "\n".join(m for (a, b), r in tests.items()
                       for m in _macros(f"{a}{b}Full{suffix}", r)) + "\n")
    da, db = tests["D", "A"], tests["D", "B"]
    log.info("crossover [%s]: D-A=%+.1f AP (t=%.1f), D-B=%+.1f AP (t=%.1f)",
             dataset, da["diff"] * 100, da["t"], db["diff"] * 100, db["t"])


# (dataset, row label, second half of the seeds only)
_PAIRED_ROWS = [("elliptic", "Elliptic", False), ("ellipticpp", "Elliptic++", False),
                ("ieee_cis", "IEEE-CIS", False), ("dgraph", "DGraph-Fin", False),
                ("s_ffsd", "S-FFSD", False), ("ethereum", "Ethereum", False),
                ("ethereum", "Ethereum, 2nd half", True)]


def _fmt_gap_p(r: Dict[str, float]) -> str:
    """Table cell like '+1.2 (0.013)': gap in AP points, two-sided p in small type."""
    if r["diff"] != r["diff"]:
        return "--"
    p = r["p"]
    s = "--" if p != p else _p_text(p)
    ps = f"${s}$" if s.startswith("<") else s
    return f"${_num(r['diff'] * 100, '+.1f')}$\\,{{\\scriptsize({ps})}}"


def table_paired_arms() -> None:
    """Every arm pair of the main crossover run, per dataset and label fraction.

    The arms of one run share graph, split and seeds, so the tests are paired by seed."""
    rows = []
    for ds, label, second in _PAIRED_ROWS:
        res = _load(_result(ds, "temporal_crossover.json"))
        levels = sorted(res["A_features"].keys(), key=float, reverse=True)
        for i, lv in enumerate(levels):
            blocks = {a: res[k][lv] for a, k in _ARM_KEYS.items()}
            if second:
                blocks = {a: _second_half(b) for a, b in blocks.items()}
            cells = " & ".join(_fmt_gap_p(_pair_test(blocks[a], blocks[b])) for a, b in _PAIRS)
            rows.append(f"{label if i == 0 else ''} & {float(lv):g} & {cells} \\\\")
        rows.append("\\addlinespace[2pt]")
    rows.pop()
    header = " & ".join(f"{a}$-${b}" for a, b in _PAIRS)
    body = ("% auto-generated -- paired arm tests of the main crossover run: gap in AP points (p)\n"
            f"\\begin{{tabular}}{{lc{'c' * len(_PAIRS)}}}\n\\toprule\n"
            f"Dataset & Frac. & {header} \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")
    _write("tab_paired_arms.tex", body)


_REDESIGN = [("elliptic", "Elliptic"), ("ellipticpp", "Elliptic++")]
# (left pool, right pool, row text): D on left minus D on right
_REDESIGN_PAIRS = [("xstep", "samestep", "D(cross-step) $-$ D(same-step)"),
                   ("xstep", "static", "D(cross-step) $-$ D(static)"),
                   ("samestep", "static", "D(same-step) $-$ D(static)")]
_POOLS = ["xstep", "samestep"]
_SWEEP_DATASETS = [("ieee_cis", "IEEE-CIS"), ("s_ffsd", "S-FFSD"),
                   ("ethereum", "Ethereum"), ("dgraph", "DGraph"),
                   ("elliptic", "Elliptic"), ("ellipticpp", "Elliptic++"),
                   ("elliptic_xstep", "Elliptic, cross-step"),
                   ("ellipticpp_xstep", "Elliptic++, cross-step")]


def _fmt_test(r: Dict[str, float]) -> str:
    """Table cell like '+1.2 [+0.3, +2.1], p=0.013', in AP points."""
    if r["diff"] != r["diff"]:
        return "--"
    ci = ("" if r["lo"] != r["lo"]
          else f"\\,[{r['lo']*100:+.1f}, {r['hi']*100:+.1f}]")
    return f"${_num(r['diff'] * 100, '+.1f')}{ci}$, ${_fmt_p(r['p'])}$"


def table_elliptic_redesign() -> None:
    """Arm D at full labels on the cross-step pool vs the same-step control and the static pool.

    The pools share graph, splits and seeds, so pairing by seed across files is valid."""
    rows = []
    for base, label in _REDESIGN:
        runs = {"static": _load(_result(base, "temporal_crossover.json"))}
        for pool in _POOLS:
            runs[pool] = _load(_result(f"{base}_{pool}", "temporal_crossover.json"))
        for lhs, rhs, text in _REDESIGN_PAIRS:
            if runs[rhs]["_config"]["temporal_split"] != runs[lhs]["_config"]["temporal_split"]:
                log.warning("redesign %s: %s and %s used different split protocols; skipped",
                            base, lhs, rhs)
                continue
            r = _pair_test(runs[lhs]["D_temporal_cells"][_FULL],
                           runs[rhs]["D_temporal_cells"][_FULL])
            rows.append(f"{label} & {text} & {_fmt_test(r)} \\\\")
    body = ("% auto-generated -- Elliptic redesign: arm D across candidate pools, full labels\n"
            "\\begin{tabular}{llc}\n\\toprule\n"
            "Graph & Comparison & $\\Delta$AP [95\\% CI], $p$ \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")
    _write("tab_elliptic_redesign.tex", body)


def _window_runs(ds: str) -> Dict[float, dict]:
    """Crossover runs of a dataset by omega share: temporal_crossover.json first, then the
    temporal_crossover_w*.json of the window sweep."""
    runs: Dict[float, dict] = {}
    for path in [_result(ds, "temporal_crossover.json")] + _result_glob(ds, "temporal_crossover_w*.json"):
        res = _load(path)
        runs.setdefault(round(float(res["_config"]["window_frac"]), 6), res)
    return runs


def table_window_sweep() -> None:
    """D-B at full labels for each crossover run, one row per dataset and omega."""
    rows = []
    for ds, label in _SWEEP_DATASETS:
        runs = _window_runs(ds)
        for frac in sorted(runs):
            res = runs[frac]
            c = res["_config"]
            r = _pair_test(res["D_temporal_cells"][_FULL], res["B_temporal_cols"][_FULL])
            rows.append(
                f"{label} & {100*float(frac):g}\\% & {float(c['window']):.4g} & "
                f"{100 * c['frac_cells_split']:.0f} & {100 * c['frac_cells_spanning_time']:.0f} & "
                f"{'yes' if c['temporal_arms_degenerate'] else 'no'} & {_fmt_test(r)} \\\\")
    body = ("% auto-generated -- window sweep: D-B at full labels per dataset and omega\n"
            "\\begin{tabular}{lcccccc}\n\\toprule\n"
            "Dataset & $\\omega$/span & $\\omega$ & split (\\%) & span time (\\%) & "
            "degenerate & D$-$B [95\\% CI], $p$ \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")
    _write("tab_window_sweep.tex", body)


_VARIANT_DATASETS = [("s_ffsd", "SF", "S-FFSD"), ("ethereum", "ETH", "Ethereum"),
                     ("dgraph", "DG", "DGraph-Fin")]
# (test name, left arm, right arm, row text); arms come from the main run and from
# every temporal_variants*.json of the dataset
_VARIANT_TESTS = [("ConeB", "D_cone_cells", "B_cone_cols", "Cones $-$ cone columns"),
                  ("ConeD", "D_cone_cells", "D_temporal_cells", "Cones $-$ D"),
                  ("ConeA", "D_cone_cells", "A_features", "Cones $-$ A"),
                  ("GateB", "D_temporal_gate", "B_temporal_cols", "Timed gate $-$ B"),
                  ("GateD", "D_temporal_gate", "D_temporal_cells", "Timed gate $-$ D"),
                  ("FutB", "D_future_cone_cells", "B_future_cone_cols",
                   "Future cones $-$ their columns"),
                  ("FutD", "D_future_cone_cells", "D_temporal_cells", "Future cones $-$ D"),
                  ("FutCone", "D_future_cone_cells", "D_cone_cells", "Future cones $-$ cones"),
                  ("FutA", "D_future_cone_cells", "A_features", "Future cones $-$ A"),
                  ("FutCols", "B_future_cone_cols", "B_cone_cols",
                   "Future-cone columns $-$ cone columns"),
                  ("Split", "D_temporal_cells", "D_static_cells", "D $-$ D on the uncut pool"),
                  ("StatB", "D_static_cells", "B_temporal_cols", "D on the uncut pool $-$ B"),
                  ("StatA", "D_static_cells", "A_features", "D on the uncut pool $-$ A"),
                  ("StatOwnB", "D_static_cells", "B_static_cols",
                   "D on the uncut pool $-$ its columns"),
                  ("DStatCols", "D_temporal_cells", "B_static_cols", "D $-$ uncut-pool columns"),
                  ("StatColsA", "B_static_cols", "A_features", "Uncut-pool columns $-$ A")]
# the variant tests whose macros the paper quotes (tab_crossover_summary)
_VARIANT_MACROS = {"DStatCols"}
# (macro name, config key of the cell count, config key of the apex share)
_CONE_COUNTS = [("Cones", "n_cone_cells", "frac_nodes_with_cone"),
                ("FutCones", "n_future_cone_cells", "frac_nodes_with_future_cone")]
_SAME_RUN = ("window", "window_frac", "epochs", "temporal_split")


def table_temporal_variants() -> None:
    """Temporal variants (cones, time-aware gate) at full labels.

    Each temporal_variants*.json is paired by seed with the arms of temporal_crossover.json:
    same graph, window, splits and seeds, and every arm reseeds itself."""
    rows, macros = [], []
    for ds, sfx, label in _VARIANT_DATASETS:
        main = _load(_result(ds, "temporal_crossover.json"))
        cm = main["_config"]
        pool = {k: v for k, v in main.items() if not k.startswith("_")}
        counts: Dict[str, object] = {}
        for path in _result_glob(ds, "temporal_variants*.json"):
            var = _load(path)
            cv = var["_config"]
            diff = [k for k in _SAME_RUN if cv.get(k) != cm.get(k)]
            if diff:
                log.warning("%s: %s differ from the main run; skipped", path.name, diff)
                continue
            if cv.get("seeds") != cm.get("seeds"):
                log.warning("%s (%s): seeds %s vs main %s; paired on the common seeds",
                            path.name, ds, cv.get("seeds"), cm.get("seeds"))
            pool.update({k: v for k, v in var.items() if not k.startswith("_")})
            counts.update(cv)
        # arm D at every swept window against the uncut pool; the other windows get
        # their own rows after the main-window one
        split_rows = []
        if _FULL in pool.get("D_static_cells", {}):
            for frac, run in _window_runs(ds).items():
                if frac != round(float(cm["window_frac"]), 6):
                    r = _pair_test(run["D_temporal_cells"][_FULL], pool["D_static_cells"][_FULL])
                    split_rows.append((frac, f" & D at $\\omega{{=}}{100 * frac:g}\\%$ "
                                             f"$-$ D on the uncut pool & {_fmt_test(r)} \\\\"))
        first = True
        for name, lhs, rhs, text in _VARIANT_TESTS:
            left, right = pool.get(lhs, {}), pool.get(rhs, {})
            if _FULL not in left or _FULL not in right:
                continue
            r = _pair_test(left[_FULL], right[_FULL])
            if name in _VARIANT_MACROS:
                macros += _macros(f"{name}Full{sfx}", r)
            rows.append(f"{label if first else ''} & {text} & {_fmt_test(r)} \\\\")
            first = False
            if name == "Split":
                rows += [row for _, row in sorted(split_rows)]
        for name, n_key, frac_key in _CONE_COUNTS:
            if n_key in counts:
                macros += [f"\\newcommand{{\\n{name}{sfx}}}{{{counts[n_key]:,}}}".replace(",", "{,}"),
                           f"\\newcommand{{\\cover{name}{sfx}}}{{{100 * counts[frac_key]:.0f}}}"]
        if not first:
            rows.append("\\midrule")
    if rows and rows[-1] == "\\midrule":
        rows.pop()
    body = ("% auto-generated -- temporal variants at full labels, paired over seeds\n"
            "\\begin{tabular}{llc}\n\\toprule\n"
            "Dataset & Comparison & $\\Delta$AP [95\\% CI], $p$ \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")
    _write("tab_temporal_variants.tex", body)
    _write("crossover_stats_variants.tex", "\n".join(macros) + "\n")


def main() -> int:
    global TABLES_DIR
    ap = argparse.ArgumentParser(description="Regenerate the paper's tables and statistics")
    ap.add_argument("--out-dir", type=Path, default=TABLES_DIR,
                    help="where to write the tables (default: %(default)s)")
    TABLES_DIR = ap.parse_args().out_dir
    log.info("writing tables to %s", TABLES_DIR)
    table_datasets()
    table_leaderboard()
    table_ablation()
    table_selection()
    table_secondary()
    table_synthetic()
    table_temporal_crossover("elliptic")
    # second temporal testbed
    table_temporal_crossover("dgraph", "tab_crossover_dgraph.tex",
                             "crossover_stats_dgraph.tex", suffix="DG")
    # Elliptic++: same network as Elliptic with extra features, a robustness check
    # rather than an independent dataset
    table_temporal_crossover("ellipticpp", "tab_crossover_ellipticpp.tex",
                             "crossover_stats_ellipticpp.tex", suffix="PP")
    # remaining temporal datasets (feed tab_crossover_summary)
    table_temporal_crossover("ieee_cis", "tab_crossover_ieee_cis.tex",
                             "crossover_stats_ieee_cis.tex", suffix="IC")
    table_temporal_crossover("s_ffsd", "tab_crossover_s_ffsd.tex",
                             "crossover_stats_s_ffsd.tex", suffix="SF")
    table_temporal_crossover("ethereum", "tab_crossover_ethereum.tex",
                             "crossover_stats_ethereum.tex", suffix="ETH")
    table_paired_arms()
    table_elliptic_redesign()
    table_window_sweep()
    table_temporal_variants()
    log.info("done. \\input these from the paper's sections/*.tex")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
